### ISSUE TITLE
Full year view

### ISSUE THREAD

**Issue by wheelq** [eduludi/jquery-yacal#4]
How can I get months to be next to each other? Currently one of the months is being displayed separately:

http://imgur.com/1L2jmsF

**Comment by eduludi** [comment]
Looks like there is a problem with the CSS in your browser. Can you tell me which browser are you using?

Notice that the CSS provided is a simple and basic stylesheet, just as a companion example for the JS library. The main idea is that developers are going to use their own stylesheets and HTML templates with it.
